-- Employee ID lookup by employee name.
-- Generated from employee_cell_mapping_direct.sql.
-- Run this in PostgreSQL / SQuirreL to verify employee IDs before mapping.

WITH input_employees(employee_name) AS (
    VALUES
        ('Aakash Tiwari'),
        ('Abdulkadar Naik'),
        ('Abhijit Deole'),
        ('Abhishek Vilas Dalvi'),
        ('Aditya Kumar'),
        ('Ajay Anant Kulkarni'),
        ('Akshay Balaji Khorgade'),
        ('Akshay Gajanan Janunkar'),
        ('Akshay More'),
        ('Akshay Ramchandra Bharati'),
        ('Ameya Sarvankar'),
        ('AMIT BALKRISHNA SHINDE'),
        ('Amol Rajendra Dandagavhal'),
        ('Amol Ramchandra Kamble'),
        ('Aniket Suhas Katare'),
        ('Anil Ashokrao Tupkar'),
        ('Anil Pardeshi'),
        ('Anirudha Vijay Rawat'),
        ('ANKITA ROHIT KUMAR SINGH'),
        ('Ankita Sanjayrao Jadhav'),
        ('Anuraag Singh'),
        ('Arif Subhan Shaha'),
        ('Ashish Kumar Biswal'),
        ('Ashish Ramashray Vishwakaram'),
        ('Ashish Yadav'),
        ('Ashwini Atmaram More'),
        ('Asmita Pandurang Farakte'),
        ('Asmita Vitthal Yadav'),
        ('Atul Baburao Potbhare'),
        ('Atul Nehate'),
        ('Badiuz Zaman Ahmed'),
        ('Barun Kamal Sharma'),
        ('BHAGYASHREE YASHWANT RAORANE'),
        ('Bharat Kadam'),
        ('Bhukya Naresh'),
        ('Chaitali Patil'),
        ('Chanchal kalyan Majumdar'),
        ('Chetan Mundhe'),
        ('CHETAN RAGHUNATH HADPE'),
        ('Chittrasen Nishad'),
        ('Danish Khan'),
        ('Deepak Ashok Patil'),
        ('Devendra Nilkute'),
        ('Dhirendra Pratap Singh'),
        ('Dinesh Jagannath Somwanshi'),
        ('Dipak Namdev Bhosale'),
        ('Dipali Sonawane'),
        ('Dnyaneshwar Rathod'),
        ('Durgesh Tupkar'),
        ('Earesseril Bijesh Babu'),
        ('Firoj Sherkhan Pathan'),
        ('Gajanan Sainath Kale'),
        ('GAJANAN SURESH THAKARE'),
        ('Ganesh Lokhande'),
        ('Gangadhar Shankar Chavan'),
        ('Gangadhar Yadavrao Londhe'),
        ('Gaurav Amrutkar'),
        ('Ghanshyam Mohan Patel'),
        ('Girish Gosavi'),
        ('Hardik Joshi'),
        ('Hardik Shripad Gund'),
        ('Haresh Rathod'),
        ('Hariom Pandey'),
        ('Harshal Mahesh Mhatre'),
        ('HARSHAL SUBHASH GAWAD'),
        ('Harshala Suvarna Devde'),
        ('Harshwardhan Bagde'),
        ('Hemant Vishwas Sonawane'),
        ('Hozefa Mohammed Haveliwala'),
        ('Hruta Nileshbhai Desai'),
        ('Isha Girish Shirke'),
        ('Jadhav Sharad Khandu'),
        ('Jatin Sudhakar Pimpale'),
        ('Jay Anil Jadhav'),
        ('Jitendra Mahesh Ghasle'),
        ('JIVAN CHANDU PURI'),
        ('Kajal Yogiraj Bane'),
        ('Karamjit Singh Banwait'),
        ('Karuna Wani'),
        ('Kaustubh Dattaram Bhosle'),
        ('Kaveri Kishor Khedekar'),
        ('KHUSALI OBHALIA'),
        ('Kiran J. Pawar'),
        ('Kiran Jadhav'),
        ('Kiran Macchindra Kengar'),
        ('Kiran Madhukar Patil'),
        ('KISHOR DATTARM NAGAP'),
        ('Komal Mayekar'),
        ('Kondba Ramrao Chopde'),
        ('Krishna Anant Moraye'),
        ('Krishna Chaurasiya'),
        ('LINA MAHENDRA AHIRRAO'),
        ('Lochan Pagdhare'),
        ('Madhuri Pange'),
        ('Mahesh Patil'),
        ('Mahesh Rasal'),
        ('MAHESH SURESH KHANDEKAR'),
        ('Malhar Kiran Kshirsagar'),
        ('Mallikarjun Kopuri'),
        ('Manali Dilip Koyande'),
        ('MANDAR VISHWANATH RANE'),
        ('Mangesh Dhuri'),
        ('Manish Gurunath Sedamkar'),
        ('Manoj Mali'),
        ('Manojkumar Rohidas Gund'),
        ('Mansi Ashok Warang'),
        ('Mayur Ayare'),
        ('Mayur Devrao Sukale'),
        ('MAYURI NARESH TANDEL'),
        ('Mayuri Vijay Patil'),
        ('MAYURI VIKRAM PATIL'),
        ('Md Jawed Alam'),
        ('Meghesh Satyanarayan Gatla'),
        ('Mehtab Salahuddin Qureshi'),
        ('Mihir Rajendra Shah'),
        ('Milind Gondse'),
        ('Minal Gharge'),
        ('Mohammad Sohail Mohammad Ismail Ansari'),
        ('MOHAMMED AVAISH QURESHI'),
        ('Mohini Maruti Jadhav'),
        ('Mukesh Sharma'),
        ('MUTHUKODI KODI SHEKAR NADAR'),
        ('Namdev Pawar'),
        ('Nandkishore Bhatkar'),
        ('Navnath Taware'),
        ('Neha Rahul Waghmare'),
        ('NEHA SAMIR DURGE'),
        ('Neha Shah'),
        ('Nikhil Chavan'),
        ('Nikhil Narendra Patil'),
        ('Nikita Palve'),
        ('Nilesh Pawar'),
        ('Nilesh Uttam Borade'),
        ('Ninad Kishor Alhat'),
        ('Nishant Ratnakar Sonawane'),
        ('Nitin Kannaujiya'),
        ('Parag Raju Adhave'),
        ('Parameshwar Attmaram Pawar'),
        ('Paras Dhandhaliya'),
        ('Pooja Misale'),
        ('Prabhudas Bhaskarao Bitra'),
        ('Pradeep Kailas Bhaskal'),
        ('Pradeep Manchekar'),
        ('Pradip Dattatraya Sangale'),
        ('Prajakta Kothule'),
        ('Prajakta Prabhakar Gawade'),
        ('Praksash Ganpatrao Bhukte'),
        ('Pralhad Tarakh'),
        ('PRAMOD HARIBHAU PATIL'),
        ('Prasad Purushottam Satpute'),
        ('PRASAD SUBHASH KULKARNI'),
        ('Prasanna Borkar'),
        ('Prashant Dinkar Chavan'),
        ('Prashant Prakash More'),
        ('Prashant Vasant Dingankar'),
        ('Prathamesh Raut'),
        ('PRATHMESH SHASHIKANT BAPARDEKAR'),
        ('Prathviraj Hanmantrao Biradar'),
        ('Pratik Patil'),
        ('Pratik Prakash Salvi'),
        ('Pratiksha Prakash Gavhane'),
        ('PRAVEEN RICHHARIYA'),
        ('Pravin Gurav'),
        ('Pravin Mane'),
        ('Priyanka Anil Patil'),
        ('Priyanka Jangam'),
        ('Priyanka Jijaba Sapkal'),
        ('PRIYANKA PRABHAKAR JADHAV'),
        ('Punam Nilesh Mahajan'),
        ('Raghunandan Rao'),
        ('Rahul Ashok Wagh'),
        ('Rahul Devre'),
        ('Rahul Narayan Nirmal'),
        ('Rahul Nathe'),
        ('Rahul Patil'),
        ('Rahul Surve'),
        ('RAJESH SUDHAKAR TANDEL'),
        ('Rakesh Sureshrao Hiware'),
        ('RANJEET PANDEY'),
        ('Rashi Trivedi'),
        ('Ravindra Narayan Pawar'),
        ('REENA PANDHARINATH RAWOOL'),
        ('Rekha Nitin Palve'),
        ('Rhytham Gaikwad'),
        ('Ritu Mahadev Tambe'),
        ('Rohit Balasaheb Pansare'),
        ('Rohit Lokhande'),
        ('Rohit Ramesh Mapankar'),
        ('Roshan Namdev Gondhali'),
        ('Roshani Ashok Dungu'),
        ('Rounak Patil'),
        ('Rupali Kale'),
        ('Rupesh Musale'),
        ('Rupesh Vilas Kunkawlekar'),
        ('Rushikesh Adinath Dhole'),
        ('RUTUJA DINKAR RANDHAWAN'),
        ('Saanvi Sachin Mungekar'),
        ('Sachin Gangadhar Dongre'),
        ('Sachinkumar Ramrao Deore'),
        ('SAGAR DNYANESHWAR MHASKAR'),
        ('Sagar Mallappa Kumbhar'),
        ('Sagar Nathe'),
        ('Sameer Rane'),
        ('Sameer Subhash Patil'),
        ('Sandeep Banda Patil'),
        ('Sandip Pandurang Patil'),
        ('Sanjana Suresh Patil'),
        ('Sanjay Jadhav'),
        ('Sanket Torne'),
        ('Santosh A. Satpute'),
        ('Santosh Khairnar'),
        ('Santosh Pal'),
        ('Sarwesh Upadhyay'),
        ('Satish Rajaram Salunkhe'),
        ('Satyajeet Sudhakar Mumbarkar'),
        ('Saurabh Jain Lunawat'),
        ('SAURABH RAVINDRA YATAM'),
        ('Saurabh Sakharam Dhamne'),
        ('SAYALI GITARAM ABHANG'),
        ('Sayali Laxman Sawal'),
        ('Shabbir Rahiman Shaikh'),
        ('Shailesh Kumar Gupta'),
        ('Shital Vinod Mohite'),
        ('SHRUTI SHRIKANT NAMAYE'),
        ('Siddhesh Chavan'),
        ('Snehal Anil Mulik'),
        ('Sonali Choughule'),
        ('Sonali Ravindra Sonawane'),
        ('Soniya Gaikwad'),
        ('Sreejith Nair'),
        ('SRISHTI MAHESHWARI'),
        ('Subhajit Chakraborty'),
        ('Subhash Vishwanath Shelke'),
        ('Suman Rawat'),
        ('Sunil Sabale'),
        ('Sunil Tondlekar'),
        ('Sunita Khedkar'),
        ('Sunita Sanjay Parde'),
        ('Supriya Gujar'),
        ('Suraj Bharucha'),
        ('Suraj Joshi'),
        ('Suresh Kisan Lahane'),
        ('Suryakant Ubhe'),
        ('Sushil Gurunath Ayarkar'),
        ('Sushil Khot'),
        ('Swapna Gupta'),
        ('Swapnali Salvi'),
        ('Swapnil Jagtap'),
        ('Swapnil K. Gedam'),
        ('Swapnil Kumar Rai'),
        ('Swapnil Nagraj Patil'),
        ('SWATI GOPALRAO TANWAIS'),
        ('SWATI RAHUL PATIL'),
        ('Tejas Date'),
        ('Tejas Munj'),
        ('Tejas Tulshidas Gaikwad'),
        ('Trupti Vasant Chavan'),
        ('Tushar Prakash Ganer'),
        ('Tushar Ughade'),
        ('UDAY SAMBHAJI PATIL'),
        ('Umesh Chandrakant Maragaje'),
        ('Uttam Shirole'),
        ('Vijay Tukaram Bhagate'),
        ('Vijeta Sunil Meshram'),
        ('VIKAS GOPINATH PANDEY'),
        ('Vikas Kundalik Patil'),
        ('Vikas Namdeo Lalsare'),
        ('Vishal Khaire'),
        ('Vishal Ramdas Badhe'),
        ('Vishal Sonalkar'),
        ('Vishal Vishwajeet Mane'),
        ('Yogesh Bhadale'),
        ('Yogesh Bhanudas Nikam'),
        ('YOGESH HARIRAM RAHANGDALE'),
        ('Yogesh Patil'),
        ('Yogesh Prakash shinde'),
        ('ZAIDI ZARI HAIDER ZAIDI')
), normalized_input AS (
    SELECT
        employee_name,
        upper(regexp_replace(replace(replace(employee_name, 'Â', ''), chr(160), ' '), '\s+', ' ', 'g')) AS employee_name_key
    FROM input_employees
), employee_matches AS (
    SELECT
        i.employee_name AS input_employee_name,
        e.employee_id,
        e.full_name AS employee_master_name
    FROM normalized_input i
    LEFT JOIN employee_master e
      ON upper(regexp_replace(replace(replace(coalesce(e.full_name, ''), 'Â', ''), chr(160), ' '), '\s+', ' ', 'g')) = i.employee_name_key
), match_summary AS (
    SELECT
        input_employee_name,
        count(employee_id) AS match_count,
        string_agg(employee_id::text, ', ' ORDER BY employee_id) AS employee_ids,
        string_agg(employee_master_name, ', ' ORDER BY employee_master_name) AS employee_master_names
    FROM employee_matches
    GROUP BY input_employee_name
)
SELECT
    input_employee_name,
    CASE
        WHEN match_count = 0 THEN 'NOT_FOUND'
        WHEN match_count = 1 THEN 'FOUND'
        ELSE 'DUPLICATE_NAME'
    END AS status,
    employee_ids,
    employee_master_names
FROM match_summary
ORDER BY status DESC, input_employee_name;
