#spring.datasource.url=jdbc:postgresql://10.0.1.193:5432/mahaitrecritment1
spring.datasource.url=jdbc:postgresql://localhost:5433/maharecruitment
#spring.datasource.url=jdbc:postgresql://localhost:5432/maharecruitmentpostgres

spring.datasource.username=postgres
#spring.datasource.password=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true
registration.department.otp-bypass-enabled=true
notification.sms.enabled=false
notification.email.enabled=false
