package db.postmigration;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Locale;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;

public class V110__login_logout_audit_history extends BaseJavaMigration {

    @Override
    public void migrate(Context context) {
        Connection connection = context.getConnection();
        if (!isPostgreSql(connection) || !tableExists(connection, "users")) {
            return;
        }

        JdbcTemplate jdbcTemplate = new JdbcTemplate(new SingleConnectionDataSource(connection, true));
        jdbcTemplate.execute("""
                create table if not exists login_logout_audit_history (
                    audit_id bigint generated by default as identity primary key,
                    user_id bigint,
                    username varchar(255) not null,
                    event_type varchar(10) not null,
                    event_time timestamp with time zone not null,
                    session_id_hash varchar(64) not null,
                    ip_address varchar(64),
                    user_agent varchar(500),
                    authentication_method varchar(20),
                    logout_reason varchar(40),
                    source varchar(20) not null,
                    constraint fk_login_logout_audit_user
                        foreign key (user_id) references users(id) on delete set null,
                    constraint chk_login_logout_audit_event
                        check (event_type in ('LOGIN', 'LOGOUT')),
                    constraint uk_login_logout_audit_event_session
                        unique (event_type, session_id_hash)
                )
                """);
        jdbcTemplate.execute("""
                do $$
                begin
                    if not exists (
                        select 1 from pg_constraint
                        where conname = 'fk_login_logout_audit_user'
                    ) then
                        alter table login_logout_audit_history
                        add constraint fk_login_logout_audit_user
                        foreign key (user_id) references users(id) on delete set null;
                    end if;
                    if not exists (
                        select 1 from pg_constraint
                        where conname = 'chk_login_logout_audit_event'
                    ) then
                        alter table login_logout_audit_history
                        add constraint chk_login_logout_audit_event
                        check (event_type in ('LOGIN', 'LOGOUT'));
                    end if;
                    if not exists (
                        select 1 from pg_constraint
                        where conname = 'uk_login_logout_audit_event_session'
                    ) then
                        alter table login_logout_audit_history
                        add constraint uk_login_logout_audit_event_session
                        unique (event_type, session_id_hash);
                    end if;
                end
                $$
                """);
        jdbcTemplate.execute("""
                create index if not exists idx_login_logout_audit_user_time
                on login_logout_audit_history (user_id, event_time desc)
                """);
        jdbcTemplate.execute("""
                create index if not exists idx_login_logout_audit_username_time
                on login_logout_audit_history (username, event_time desc)
                """);
        jdbcTemplate.execute("""
                create index if not exists idx_login_logout_audit_session
                on login_logout_audit_history (session_id_hash)
                """);
    }

    private boolean tableExists(Connection connection, String tableName) {
        try (ResultSet rs = connection.getMetaData().getTables(null, null, tableName, null)) {
            if (rs.next()) {
                return true;
            }
        } catch (SQLException ex) {
            return false;
        }

        try (ResultSet rs = connection.getMetaData().getTables(null, null, tableName.toUpperCase(Locale.ROOT), null)) {
            return rs.next();
        } catch (SQLException ex) {
            return false;
        }
    }

    private boolean isPostgreSql(Connection connection) {
        try {
            String databaseProductName = connection.getMetaData().getDatabaseProductName();
            return databaseProductName != null
                    && databaseProductName.trim().toLowerCase(Locale.ROOT).contains("postgresql");
        } catch (SQLException ex) {
            return false;
        }
    }
}
