package db.postmigration;

import java.sql.Statement;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

public class V128__employee_tax_invoice_storage extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        try (Statement statement = context.getConnection().createStatement()) {
            statement.execute("""
                    create table if not exists employee_tax_invoice (
                        id bigint generated by default as identity primary key,
                        generation_token varchar(36) not null unique,
                        department_id bigint not null,
                        sub_department_id bigint,
                        project_id bigint not null,
                        period_start date not null,
                        period_end date not null,
                        ti_number varchar(50) not null unique,
                        ti_date date not null,
                        request_id varchar(100) not null,
                        project_name text not null,
                        billed_to varchar(255) not null,
                        total_amount numeric(14,2) not null,
                        generated_on timestamp not null,
                        generated_by varchar(255) not null,
                        invoice_snapshot text not null,
                        constraint chk_employee_tax_invoice_period check (period_end >= period_start)
                    )
                    """);
            statement.execute("""
                    create index if not exists idx_employee_tax_invoice_generated
                    on employee_tax_invoice (generated_on desc, id desc)
                    """);
        }
    }
}
