package db.postmigration;

import java.sql.Statement;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

/** One row per employee billed on an employee tax invoice, used to stop billing the same days twice. */
public class V129__employee_tax_invoice_line extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        try (Statement statement = context.getConnection().createStatement()) {
            statement.execute("""
                    create table if not exists employee_tax_invoice_line (
                        id bigint generated by default as identity primary key,
                        employee_tax_invoice_id bigint not null
                            references employee_tax_invoice (id) on delete cascade,
                        line_number integer not null,
                        employee_id bigint not null,
                        employee_code varchar(100),
                        employee_name varchar(255) not null,
                        designation_name varchar(255),
                        level_code varchar(50),
                        billed_from date not null,
                        billed_to date not null,
                        rate_per_month numeric(14,2),
                        amount numeric(14,2) not null,
                        constraint uk_employee_tax_invoice_line_employee unique (employee_tax_invoice_id, employee_id),
                        constraint chk_employee_tax_invoice_line_period check (billed_to >= billed_from)
                    )
                    """);
            statement.execute("""
                    create index if not exists idx_employee_tax_invoice_line_employee_period
                    on employee_tax_invoice_line (employee_id, billed_from, billed_to)
                    """);
        }
    }
}
