package db.postmigration;

import java.sql.Statement;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

public class V142__employee_type_conversion_audit extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        try (Statement statement = context.getConnection().createStatement()) {
            statement.execute("""
                    create table if not exists employee_type_conversion_audit (
                        audit_id bigint generated by default as identity primary key,
                        employee_id bigint not null,
                        employee_name varchar(150) not null,
                        employee_code varchar(50),
                        source_type varchar(20) not null,
                        target_type varchar(20) not null,
                        department_id bigint not null,
                        department_name varchar(100) not null,
                        cell_id bigint,
                        cell_name varchar(180),
                        reporting_hod_user_id bigint,
                        reporting_hod_name varchar(255),
                        manager_type varchar(10),
                        reporting_manager_employee_id bigint,
                        reporting_manager_name varchar(255),
                        actor_login_id varchar(255) not null,
                        occurred_at timestamp not null default current_timestamp
                    )
                    """);
            statement.execute("""
                    create index if not exists idx_emp_type_conversion_employee
                    on employee_type_conversion_audit (employee_id)
                    """);
            statement.execute("""
                    create index if not exists idx_emp_type_conversion_occurred
                    on employee_type_conversion_audit (occurred_at desc)
                    """);
        }
    }
}
